[package]
name = "blockchain-sync"
version = "0.1.0"
authors = ["Your Name"]
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
sha2 = "0.9"
log = "0.4"
env_logger = "0.9"
libp2p = { version = "0.43", features = ["tcp-tokio", "dns-tokio"] }


